const [
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
] = [
  400,
  401,
  403,
  404,
  409,
  500,
];

module.exports = {
  badRequest: {
    status: BAD_REQUEST,
    code: 400,
    message: 'Mauvaise demande',
    payload: null,
  },
  converterInvalid: {
    status: BAD_REQUEST,
    code: 4001,
    message: 'Le convertisseur n\'est pas valide',
    payload: null,
  },
  statusInvalid: {
    status: BAD_REQUEST,
    code: 4002,
    message: 'Le statut n\'est pas valide',
    payload: null,
  },
  timeInvalid: {
    status: BAD_REQUEST,
    code: 4003,
    message: 'La date et l\'heure sont invalides',
    payload: null,
  },
  canNotUUpdatePackage: {
    status: BAD_REQUEST,
    code: 4004,
    message: 'Le produit dans le package a été utilisé, ne peut pas mettre à jour ce package',
    payload: null,
  },
  isNotANumber: {
    status: BAD_REQUEST,
    code: 4005,
    message: 'La valeur doit être numérique',
    payload: null,
  },

  unauthorized: {
    status: UNAUTHORIZED,
    code: 401,
    message: 'Non autorisé',
    payload: null,
  },
  requireAuthToken: {
    status: UNAUTHORIZED,
    code: 4011,
    message: 'Une autorisation est requise',
    payload: null,
  },
  invalidAuthToken: {
    status: UNAUTHORIZED,
    code: 4014,
    message: 'Autorisation invalide',
    payload: null,
  },
  tokenExpired: {
    status: UNAUTHORIZED,
    code: 4015,
    message: 'Autorisation expirée',
    payload: null,
  },

  forbidden: {
    status: FORBIDDEN,
    code: 403,
    message: 'Interdit',
    payload: null,
  },
  userIsBlocked: {
    status: FORBIDDEN,
    code: 4031,
    message: 'L\'utilisateur est bloqué',
    payload: null,
  },
  userNotActive: {
    status: FORBIDDEN,
    code: 4032,
    message: 'L\'utilisateur n\'est pas actif',
    payload: null,
  },
  productIsUnavailable: {
    status: FORBIDDEN,
    code: 4033,
    message: 'Impossible d\'utiliser ce produit',
    payload: null,
  },
  userNotHavePermision: {
    status: FORBIDDEN,
    code: 4034,
    message: 'Vous n\'êtes pas autorisé à effectuer cette action',
    payload: null,
  },

  notFound: {
    status: NOT_FOUND,
    code: 404,
    message: 'Pas trouvé',
    payload: null,
  },
  emailNotFound: {
    status: NOT_FOUND,
    code: 4041,
    message: 'L\'adresse e- mail n\'est associée à aucun compte. Vérifiez votre adresse e-mail et réessayez.',
    payload: null,
  },
  userNotFound: {
    status: NOT_FOUND,
    code: 4042,
    message: 'Utilisateur non trouvé',
    payload: null,
  },
  tokenResetPasswordNotFound: {
    status: NOT_FOUND,
    code: 4043,
    message: 'Le jeton de réinitialisation du mot de passe est invalide ou a expiré',
    payload: null,
  },
  workplaceNotFound: {
    status: NOT_FOUND,
    code: 4044,
    message: 'Lieu de travail introuvable',
    payload: null,
  },
  notificationNotFound: {
    status: NOT_FOUND,
    code: 4045,
    message: 'Notification introuvable',
    payload: null,
  },
  productNotFound: {
    status: NOT_FOUND,
    code: 4046,
    message: 'Produit non trouvé',
    payload: null,
  },
  logoutFailed: {
    status: NOT_FOUND,
    code: 4047,
    message: 'Échec de la déconnexion',
    payload: null,
  },
  comparePasswordFailed: {
    status: NOT_FOUND,
    code: 4048,
    message: 'Saisie du mot de passe incorrect',
    payload: null,
  },
  loginFailed: {
    status: NOT_FOUND,
    code: 4049,
    message: 'L\'identifiant ou le mot de passe est incorrect!',
    payload: null,
  },
  restaurantNotFound: {
    status: NOT_FOUND,
    code: 40490,
    message: 'Aucun restaurant trouvé',
    payload: null,
  },
  codeNotFound: {
    status: NOT_FOUND,
    code: 4050,
    message: 'Je ne trouve pas le code de ce produit',
    payload: null,
  },
  productPackageNotFound: {
    status: NOT_FOUND,
    code: 4051,
    message: 'Paquet de produit introuvable',
    payload: null,
  },
  productAndProductPackageNotFound: {
    status: NOT_FOUND,
    code: 4052,
    message: 'Produit et emballage de produit introuvables',
    payload: null,
  },
  productIndexNotFound: {
    status: NOT_FOUND,
    code: 4053,
    message: 'Le produit d\'origine n\'existe pas ou a été fusionné avec un autre produit',
    payload: null,
  },

  updateFailed: {
    status: CONFLICT,
    code: 4090,
    message: 'Mise à jour a échoué',
    payload: null,
  },
  conflict: {
    status: CONFLICT,
    code: 409,
    message: 'Conflit',
    payload: null,
  },
  userExists: {
    status: CONFLICT,
    code: 4091,
    message: 'L\'utilisateur existe déjà',
    payload: null,
  },
  phoneExists: {
    status: CONFLICT,
    code: 4092,
    message: 'Le numéro de téléphone existe',
    payload: null,
  },
  emailExists: {
    status: CONFLICT,
    code: 4093,
    message: 'l\'email existe déjà',
    payload: null,
  },
  restaurantExists: {
    status: CONFLICT,
    code: 4094,
    message: 'Le restaurant existe déjà',
    payload: null,
  },
  usernameExists: {
    status: CONFLICT,
    code: 4095,
    message: 'Ce nom d\'utilisateur existe déjà',
    payload: null,
  },
  checkAccept: {
    status: CONFLICT,
    code: 4096,
    message: 'Veuillez accepter les conditions',
    payload: null,
  },
  scanTheScannedProduct: {
    status: CONFLICT,
    code: 4097,
    message: 'Le produit est déjà utilisé, veuillez choisir un autre produit',
    payload: null,
  },
  compareNewPassword: {
    status: CONFLICT,
    code: 4098,
    message: 'Votre nouveau mot de passe est le même que votre ancien mot de passe',
    payload: null,
  },
  productWasChecked: {
    status: CONFLICT,
    code: 4099,
    message: 'Ce produit a été vérifié',
    payload: null,
  },
  productCodeWasCreated: {
    status: CONFLICT,
    code: 4090100,
    message: 'Le code du produit a été créé',
    payload: null,
  },
  productPackageWasSaved: {
    status: CONFLICT,
    code: 4090101,
    message: 'Ce package de produit a été enregistré dans le système',
    payload: null,
  },
  productWasNotChecked: {
    status: CONFLICT,
    code: 4090102,
    message: 'Ce produit n\'a pas été vérifié',
    payload: null,
  },
  productPackageWasNotScan: {
    status: CONFLICT,
    code: 4090103,
    message: 'L\'emballage du produit n\'a pas été scanné',
    payload: null,
  },
  productPackageWasScan: {
    status: CONFLICT,
    code: 4090104,
    message: 'L\'emballage du produit a été scanné',
    payload: null,
  },
  someProducWasUsing: {
    status: CONFLICT,
    code: 4090105,
    message: 'Ce produit est en cours d\'utilisation.Vous ne pouvez pas modifier',
    payload: null,
  },
  invalidStatus: {
    status: CONFLICT,
    code: 4090106,
    message: 'Statut invalide',
    payload: null,
  },
  skuIsExist: {
    status: CONFLICT,
    code: 4090107,
    message: 'Le produit existe dans ce package',
    payload: null,
  },

  serverError: {
    status: INTERNAL_SERVER_ERROR,
    code: 500,
    message: 'Erreur Interne du Serveur',
    payload: null,
  },
};
